title: Archana Sathiyaseelan
logo: /assets/img/profileimage.jpg
description: Data Scientist with advanced knowledge in machine learning and python development


show_downloads: true
theme: jekyll-theme-minimal
